name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]
    
    name: Java ${{ matrix.java }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn --batch-mode --no-transfer-progress clean compile -Dgpg.skip=true
    
    - name: Run tests
      run: mvn --batch-mode --no-transfer-progress test -Dgpg.skip=true
    
    - name: Verify
      run: mvn --batch-mode --no-transfer-progress verify -Dgpg.skip=true